name: glacier
version: 0.0.1
description: Markdown Doc Gen in dart
homepage: https://github.com/nyxx/glacier

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  yaml: ^3.1.0
  path: ^1.8.0

executables:
  glacier:
