name: glacier
version: 0.2.0
description: Markdown Doc Gen in dart
homepage: https://github.com/nyxx/glacier

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.2.0
  http: ^0.13.3
  logger: ^1.0.0
  markdown: ^4.0.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  yaml: ^3.1.0

executables:
  glacier:
